name: Staging Deploy

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'staging')
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Prep ssh access
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com  >> ~/.ssh/known_hosts
          ssh-agent -a ${{ env.SSH_AUTH_SOCK }} > /dev/null
          ssh-add - <<< "${{ secrets.SSH_DEPLOY_KEY }}"

      - name: Set Up Repo
        run: |
          git remote add staging git@github.com:badgateway/staging.badgateway.net.git
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch --unshallow origin
          git checkout -b temp-staging-deploy

      - name: Update CNAME
        run: |
          echo www.staging.badgateway.net > CNAME
          git add CNAME
          git commit -m "Update CNAME"

      - name: Push to Staging Repo
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: git push -u staging temp-staging-deploy:deploy --force
